# Generated by Django 4.0.5 on 2022-07-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='closed_temporaily',
            new_name='closed_temporarily',
        ),
    ]
