# Generated by Django 4.0.5 on 2022-07-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_closed_temporaily_place_closed_temporarily'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='menu',
            new_name='menus',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
    ]
